version: '3'
services:
  db:
    hostname: mysql
    image: mysql:8.0.23
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "ms23@ingress"
    ports:
      - "3306:3306"
#    networks:
#      - db
  ms-23-students:
    image: arabkhan/student-ms:1.0.6544586
    restart: always
    environment:
        - DB_CONNECTION_IP=db
        - DB_CONNECTION_USERNAME=root
        - DB_CONNECTION_PASSWORD=ms23@ingress
    ports:
      - "9094:9094"
    depends_on:
      - db
#    networks:
#      - db
  ms-23-users:
    image: arabkhan/user-ms:1.0.6544586
    restart: always
    environment:
      - DB_CONNECTION_IP=db
      - DB_CONNECTION_USERNAME=root
      - DB_CONNECTION_PASSWORD=ms23@ingress
    ports:
      - "9095:9095"
    depends_on:
      - db
#    networks:
#      - db
  adminer:
    hostname: mysql
    image: adminer
    restart: always
    ports:
      - "8580:8080"
#    networks:
#      - db
  reverse_proxy:
    image: nginx:1.23
    hostname: proxy
    container_name: reverse_proxy
    ports:
      - "8000:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - ms-23-students
      - ms-23-users
#    networks:
#      - db

volumes:
  db_data:

#networks:
#  db:
